### ISSUE TITLE
Updating Tags in a blog post doesn't update

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/Blog#101]
When updating a blog post and changing the tags, after change those tags are not visible in the overview page nor in the search (for tags).

## Root-Cause
When entering the update blog post page, the blog post is retrieved from the cache rather than the underlying repository.
That leads to the problem, that the children are not tracked anymore and therefore don't get updated.

## Test to reproduce
```csharp
[Fact]
public async Task GivenBlogPostWithTags_WhenLoadingAndDeleting_ThenShouldBeUpdated()
{
    var bp = new BlogPostBuilder().WithTags("tag 1").Build();
    var sut = new CachedRepository<BlogPost>(Repository, new MemoryCache(new MemoryCacheOptions()));
    await sut.StoreAsync(bp);
    var updateBp = new BlogPostBuilder().WithTags("tag 2").Build();
    var bpFromCache = await sut.GetByIdAsync(bp.Id);
    bpFromCache.Update(updateBp);
    await sut.StoreAsync(bpFromCache);

    var bpFromDb = await sut.GetByIdAsync(bp.Id);

    bpFromDb.Tags.Single().Content.Should().Be("tag 2");
}
```

**Comment by linkdotnet** [comment]
For SQL can be solved like this: https://devblogs.microsoft.com/dotnet/announcing-ef8-preview-4/

**Comment by linkdotnet** [comment]
@manishtiwari25 I have a open PR (#252) that fixes the issue. Would like to get your input on this one.
Basically it uses the ef8 preview 4 feature of OPEN_JSON to make the code way simpler.

My concern right now is that we need a migration script, that adds the new column and fills it with all the pre-populated values. Otherwise I am pretty fine with the changes.

**Comment by manishtiwari25** [comment]
looks good and I was also thinking the same approach, I will test it in MySQL and let you know, or make changes if needed. 
thanks for fixing :)

**Comment by manishtiwari25** [comment]
can't test now, because Pomelo.EntityFrameworkCore.MySql doesn't support EF Core 8, they have opened an [issue](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/1746). I will raise a PR after they release something related to this.

**Comment by linkdotnet** [comment]
Okay - thanks for the link. Yeah might not be ideal that I broke the current version in combination with MySQL :D
