### ISSUE TITLE
Unable to add new blog post

### ISSUE THREAD

**Issue by manishtiwari25** [linkdotnet/Blog#188]
Submit button while writing a new blog is always disabled. 
I checked the code and found that canSubmit variable is set to true. 
I think it should be false by default. what do you think? 

![image](https://user-images.githubusercontent.com/50008945/227532135-730a9758-171b-4724-8f38-f24c76688e7a.png)
![image](https://user-images.githubusercontent.com/50008945/227532165-94e0280f-e4f0-4d98-bbe0-82252fd9b90e.png)
![image](https://user-images.githubusercontent.com/50008945/227532194-6982a474-6d89-4906-89a8-8de67cf8eab4.png)

**Comment by linkdotnet** [comment]
Dadoi - yes :D I mixed the `disabled` attribute. 
I fixed it with commit e514560

**Comment by linkdotnet** [comment]
Thanks for reporting the issue. If you pull the latest master, it should work again.
