### ISSUE TITLE
Use `IOptions` pattern instead of `AppConfiguration` and `AppConfigurationFactory`

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/Blog#273]
In its current implementation, there is only one object `AppConfiguration` that is created by `AppConfigurationFactory`.

We could replace this all with `IOptions<T>` and use validationattributes on the objects. The usage in certain scenarios would be way easier.

**Comment by manishtiwari25** [comment]
@linkdotnet need any help with this?

**Comment by linkdotnet** [comment]
Oh absolutely! A helping hand here is very welcome.
