### ISSUE TITLE
MongoDB support

### ISSUE THREAD

**Issue by vincentnacar02** [linkdotnet/Blog#281]
Would be great if this could support MongoDB as well.

**Comment by linkdotnet** [comment]
Good point @vincentnacar02  - unfortunately I don't have much experience with **MongoDB** itself.
Is there an easy way to run a server somewhere (like Azure)?

**Comment by vincentnacar02** [comment]
Hi @linkdotnet you can check MongoDB atlas (https://www.mongodb.com/) They have a free option

**Comment by linkdotnet** [comment]
Hey @vincentnacar02 I added support for mongodb - thanks for the link.

You can use MongoDB like this:
```json
"PersistenceProvider": "MongoDB",
"ConnectionString": "your-connection-string",
"DatabaseName": "my-db",
```

Let me know if you encounter some rough edges.

**Comment by vincentnacar02** [comment]
Great! That was fast. Thanks, I'll check it out and let you know

**Comment by linkdotnet** [comment]
Yeah it was kind of straightforward and I played around some stuff - but there is a chance that there are still exceptional cases.
