### ISSUE TITLE
SqlServer Unhandled Exception

### ISSUE THREAD

**Issue by GraemeWellington** [linkdotnet/Blog#291]
I am using Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.8.0 Preview 1.0
I have installed the latest .NET8 SDK Version="8.0.0-rc.1.23421.29"

I implemented PersistenceProvider": "SqlServer and the system built the database ok. I logged in and went to Administrator and created 1 blog and submitted ok. However returning to the dashboard an unhandled exception error was encountered. After each restart the same error.

Just to get things working I tracked down the problem to: LinkDotNet.Blog.Domain BlogPost.cs line 28:

public IReadOnlyCollection<string> Tags { get; private set; }

I changed this to:

public IList<string> Tags { get; private set; }

This created a build error in: LinkDotNet.Blog.Web.Controller RssFeedContoller.cs line 98:

            s => new BlogPostRssInfo(s.Id, s.Title, s.ShortDescription, s.UpdatedDate, s.PreviewImageUrl, s.Tags),

I changed this to [add explicit cast]:

            s => new BlogPostRssInfo(s.Id, s.Title, s.ShortDescription, s.UpdatedDate, s.PreviewImageUrl, (IReadOnlyCollection<string>)s.Tags),

Then all worked.

**Comment by linkdotnet** [comment]
Hey thanks for reporting the issue.

This is a known regression from preview 7 to rc 1: https://github.com/dotnet/efcore/issues/31722

That said, I will most likely revert the last commit with the update until the issue got fixed.

**Comment by linkdotnet** [comment]
I reverted the last upgrade on `master`. That should make everything work again.

**Comment by GraemeWellington** [comment]
OK great - awesome project!

**Comment by linkdotnet** [comment]
> OK great - awesome project!

Thanks - if you have other issues/requests let me know.
