### ISSUE TITLE
Create wiki-page for initial setup

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/Blog#32]
Ideas:
- [ ] having a wiki page how to set up everything
- [ ] Interactive setup when the blog is loaded the first time

For the second one we need way more stuff beforehand.

**Comment by bizcad** [comment]
Do you have a wiki page started?  I have cloned the repo and have been modifying it for my blog.  I ran into a couple of road blocks and would like to contribute the setup documentation to smooth the path for others.

For example, I set up a localhost docker sql database to persist the posts.  It took me a while to realize that the way implement the IEntityTypeConfiguration<T> creates the tables.  A very useful and advanced (to me) technique that could use some more explanations.

**Comment by linkdotnet** [comment]
Hey @bizcad thanks for reaching out. Unfortunately I did not create a real wiki-page guiding through the onboarding process. So this is up for grabs :D. I had hoped the README.md is a good enough starting point.

I do understand the confusion that the database is created automatically. My thought process was that I wanted to align all the storage provider (RavenDb, SQLite, SQL Server) to behave the same. Maybe something which at least should be explained in the README.md. 

I will take this up. Let me know if you encounter other issues or you need a helping hand. Happy to discuss.

**Comment by bizcad** [comment]
Hello Steven,

 

Thanks for getting back to me.  

 

I love the idea of the database being created automagically.  I will start using this technique in my development.  It makes so much more sense to let the EF and DBContext handle it.  

 

I use SQL Express in a Docker container for my database.  For a lot of my applications I do not need, or want to pay for a full blown Sql Server.  SQL Express is great for small databases.  

 

I would be happy to put in a pull request to change the README.md

 

Nick Stein

61 Bennington

Irvine, CA 92620

949-394-3466 iPhone

**Comment by linkdotnet** [comment]
Hey Nick,

today I added a very small passage to the README.md explaining that on SQL the database will be created automatically. A more in-depth explanation is much welcome. Especially because from my point of view everything "seems logical", but that tunnel vision is often times not that great ;)

So if you have time to spare, I would welcome a helping hand.

Cheers
Steven

**Comment by linkdotnet** [comment]
Fixed by #257
