### ISSUE TITLE
Feedback: Make using preview (.NET9) opt-in

### ISSUE THREAD

**Issue by modestotech** [linkdotnet/Blog#333]
Thought about trying out the blog but now, 60 minutes plus later, it's still not running because of different .NET9 preview issues. I haven't used .NET9 before. 

Surely solvable but not anything I'd like to put time into when my focus was to try out the blog, so for the future I'd appreciate preview stuff to be opt-in.

**Comment by linkdotnet** [comment]
That could be an option - currently that is more of a documentation issue.

The basic idea is to use the "stable tags" like: https://github.com/linkdotnet/Blog/releases/tag/v8.0
There is no preview stuff in them, but that is not obvious at the moment, leading to those issues.

I am not sure whether it's straightforward to opt in (especially with some of the Nuget packages).
Another option is to have an `unstable` or `dev`branch.

**Comment by modestotech** [comment]
But the project is bumped to .net9, how do you mean that stable tags should be used?

I guess that there could be a branch for unstable/preview target framework?

Some background on the problems:
1. First VS didn't find the .NET9 installation. Uninstalling and installing .NET9 didn't solve. Restart did solve.
2. Then this error: `The analyzer assembly references version '4.11.0.0' of the compiler, which is newer than the currently running version '4.10.0.0'.`. Solved by installing VS 2022 Preview. [More on this issue](https://stackoverflow.com/questions/76740942/how-to-fix-the-analyzer-assembly-references-version-4-7-0-0-of-the-compiler).
3. Now I'm stuck with the error below, if you'd know the solution I'd appreciate it to get rolling with the blog :)

![image](https://github.com/linkdotnet/Blog/assets/31730051/583f6964-c224-4501-8632-2bb5206e2b52)

**Comment by linkdotnet** [comment]
The `main` branch contains the latest and greatest state, i.e. `net9.0-preview` at the moment.
You can checkout the `v8.0` tag to go to `net8.0`:
```bash
git checkout v8.0
```

This points to a commit where `net8.0` is "still" used removing the need to install `net9.0` and the latest Visual Studio Preview.

**Comment by modestotech** [comment]
Thanks, that clarified! I'm now running the v8.0 tag. 
Maybe something about this strategy would be nice in the README? In my experience master/main is the released/stable code so maybe not obvious for other people as well.

**Comment by linkdotnet** [comment]
Yeah, that is what I meant about a documentation issue! I totally missed that, so thanks for bringing this up @modestotech 

But going forward, the approach of using `master`/`main` as the stable version might be more suitable. I will make myself some thoughts.

**Comment by linkdotnet** [comment]
I added a comment in the setup section explaining the difference between `master` and the tags.
In the future I will pivot towards `master`/`main` and a `dev` or `unstable` branch. As I already have unstable stuff on `master` I will do the cut once .net9 is stable.

Hope that makes sense. Thanks again for reporting @modestotech

**Comment by modestotech** [comment]
Looks great @linkdotnet, well done although I think that requiring people that wants to contribute to use .NET previews isn't great (as you've written that contributors should use `develop`). Furthermore, if work are being done in the `dev`/`unstable` branch that requires preview features, you won't be able to merge into `main` until .NET9 has been released.

I'd keep `main` and `dev` with production ready stuff, not dependent on .NET preview, and an unstable branch besides those, that can be based on `develop`, and introducing new preview features, that can be merged into develop when MS released the next .NET version.

I might want to contribute but I don't want to "waste" time troubleshooting .NET preview stuff, therefore above would work for me.

**Comment by linkdotnet** [comment]
The problem is that Blazor is "kind of new," and therefore, some features I really want to use are only available in the preview. 

But maybe I can pivot in the future to take a more "stable" approach.

**Comment by modestotech** [comment]
Fair enough! Creates a barrier for people that want to contribute but then it's for a good reason 👍
