### ISSUE TITLE
Shortcodes

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/Blog#352]
The user should have the possibility to define dynamic content (markdown) that is shown at the bottom of every blog post.

CC: @ncosentino

**Comment by linkdotnet** [comment]
Hey @ncosentino,

The feature is in a "almost-finished" state. So practically 5 month away from production. Just kidding.
Anyway, my question to you is where to add the shortcode.

That is my current approach:

```no-class
+-----------------------+
+     HEADER            +
+-----------------------+
+                       +
+       BODY            +
+                       +
+-----------------------+
+ LIKE/SHARE            +
+-----------------------+
+    DONATION STUFF     +
+-----------------------+
+       SHORT CODE      +
+-----------------------+
+ READ MORE/RELATED     +
+-----------------------+
```

**Comment by ncosentino** [comment]
5 months?! Marketing needed this last week! 

My short code usage is generally throughout the article:
- I may have one or two short codes in an article for particular courses
- I may use a shortcode in the article for a digital product
- I was previously using a shortcode on WordPress to put a reusable social media icon list (but this is not very important) 

But short answer: it's not a fixed location for me how I leverage them

**Comment by linkdotnet** [comment]
Interesting. Given that you have only Markdown to add those shortcodes and nothing like drag 'n drop, how would you imagine adding those shortcodes throughout the article?

**Comment by ncosentino** [comment]
Honestly just as simple as some type of special annotation would be great.

If I know there's a list of shortcodes with IDs and I'm allowed to manually
put anywhere something like [[SHORT_001]] then I'm very happy.

This is essentially what I had to do in WordPress anyway! Open the list of
shortcodes, pick the one I want, copy paste into the post!

(Also zero opinion on the usage syntax, I was just making something random
up)

**Comment by linkdotnet** [comment]
Hey @ncosentino 

I have a working prototype and wanted to grab some feedback from you. Here is the current usage as a small gif:
![shortcode](https://github.com/user-attachments/assets/498414e0-d1f6-4f60-8e4e-68f619d02a58)

So basically you can manage a list of "shortcodes"/"templates" which can be dropped in into the editor. Changing them in the admin page, will immediately reflect inside the blog post.

Current limitations:

1. The shortcode is only copied into the clipboard as **EasyMDE** currently doesn't give an easy hook into the current cursor positions.
2. **EasyMDE** has a custom toolbar, but only allows very primitive things. Therefore the position of the button is now somewhat floating inside the editor.
3. Shortcodes are not part of the toc, even though they might contain headers. They are also not part of the reading time!
4. Shortcodes don't work in the description. There is no technical limitation, but I felt it doesn't make that much sense.

Just wanted to get your impression and how much it covers of your use cases.

**Comment by ncosentino** [comment]
This is perfect from my use cases -- even easier to use than what I was used to in WordPress. Love it!

**Comment by linkdotnet** [comment]
Awesome - merged it into `master`.

As I don't have EF Migrations in place at the moment, you would have to do this manually: [MIGRATION.md](https://github.com/linkdotnet/Blog/blob/master/MIGRATION.md).
