### ISSUE TITLE
Table of Contents should respect "raw" HTML tags

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/Blog#353]
Currently, only markdown is parsed, but `<h2...>` and friends should also work.

While working on this feature, there are some major complexity points here: mainly:

Do we want to allow a mixed mode? So there are `#` in the code and `<h1>` and friends.

Markdig doesn't support parsing HTML elements out of the box - therefore, we might need to use something like Anglesharp to parse the HTML itself.

For the time being, keeping the HTML Toc (if there is one) might be the easier solution.

**Comment by linkdotnet** [comment]
An alternative is something like: https://github.com/mysticmind/reversemarkdown-net

We could offer a button that just converts all the HTML to markdown. That would also solve the problem.

**Comment by FrancescoRepo** [comment]
Hi @linkdotnet,
I'm available to work on this feature to add the button to convert HTML to markdown using the library you mentioned: https://github.com/mysticmind/reversemarkdown-net
This button should convert all the HTML to markdown and also give the possibility to restore the original content in case the user wants to go back.

I was also thinking, not totally related to this feature, but to add a "Preview" button near the "Submit" button when you create the post to show what it'll look like in a full-screen modal. This, of course, means refactoring the ShowBlogPostPage to extract the BlogPost detail in its component and other little stuff.

If it's ok with you, I can work on it!

**Comment by linkdotnet** [comment]
Closes by #381
