### ISSUE TITLE
Error when closing notification

### ISSUE THREAD

**Issue by digitaldirk** [linkdotnet/Blog#356]
**When closing a notification an error occurs:**
![errornotification](https://github.com/user-attachments/assets/4bba844e-e07e-48a9-b5f9-2145874b831e)

Tested on Edge, Chrome, Firefox on desktop and mobile.

**Comment by linkdotnet** [comment]
Well - that is related to local storage. I am not sure why that happens. 
In any case, I probably will remove the promotion. 

Thanks for bringing this to my attention @digitaldirk

**Comment by linkdotnet** [comment]
That should be resolved, as I removed the promotion
