### ISSUE TITLE
Enable upload of images / markdown via Drag and Drop when creating blog post

### ISSUE THREAD

**Issue by linkdotnet** [linkdotnet/Blog#41]
Option: use inputfile

**Comment by francofgp** [comment]
How do you upload an image with Drag and Drop?

I am trying and this is what I get:
![ezgif com-video-to-gif](https://github.com/linkdotnet/Blog/assets/70602890/78146c47-9b01-42d1-8d13-c1f83a94f6ae)


![image](https://github.com/linkdotnet/Blog/assets/70602890/33535052-3215-41c2-8af5-2686d6155137)

Do I have to active a function?
I just Cloned the repo today

**Comment by linkdotnet** [comment]
Hey @francofgp ,

You did nothing wrong, nor did you have to activate a function.
The upload of pictures does not work - or better, it just interprets it as text. Shame on me that I never documented this.

The problem with the picture upload is that I need a valid target (like Azure Blob Storage, Amazon S3 Bucket, ...) to upload the file. Also, a useful filename might be something - you can probably use the input filename, but you might run into duplicated files or so. Alternatively, create just some random id.

If you have an idea, I would suggest you can open a new issue on how it should work for you.
